# 每轮参数模板：复制后填写 ARM64_VC_ENV；parse_env.py 只解析赋值，不执行文件。
# 只允许必填／可选键及对前面已定义键的引用。REPLACE_* 必须替换，模板原样执行会拒绝。
# 下面版本仅演示目录关系，实际版本、模型、账号、摘要、认证与来源由本轮批准输入确定。
ROUND=round1
STAMP=YYYYMMDDtHHMMSSz
BASELINE_VERSION=9.0.0
TARGET_VERSION=9.1.0
TARGET_PROFILE_ID=codex-$TARGET_VERSION-official
D=/root/docker/capture-cli/data
RUNROOT=/root/vc-rounds/$ROUND
NEW=codex-$TARGET_VERSION-formal-$ROUND-$STAMP
IN=codex-$TARGET_VERSION-inputs-$ROUND-$STAMP
UP=codex-$BASELINE_VERSION-to-$TARGET_VERSION-$ROUND-$STAMP
CAND=codex-$TARGET_VERSION-candidate-$ROUND
B=$D/candidates/$CAND
PREV_CANDIDATE=$D/candidates/REPLACE_PREVIOUS_CANDIDATE
HISTORY_TEST_TREE=$D/candidates/REPLACE_HISTORY_CANDIDATE/test-tree
# C 是候选提交，DC 是其冻结承接提交；不得使用缩写。
C=0000000000000000000000000000000000000000
DC=0000000000000000000000000000000000000000
RECEIPT=docs/egress/maintenance/REPLACE_FREEZE_SUCCESSOR.json
BUNDLE=$D/staging/$ROUND.bundle
BUNDLE_BRANCH=codex/REPLACE_CANDIDATE_BRANCH
# 新目标首次取证必须 recapture。reuse 仅限同一目标的可信官方证据恢复。
EVIDENCE_DECISION=recapture
PREDECESSOR_CAMPAIGN=$D/evidence/campaigns/REPLACE_PREDECESSOR
OFFICIAL_CAMPAIGN=$PREDECESSOR_CAMPAIGN
OFFICIAL_STOP_LEDGER=$D/control/REPLACE_PREDECESSOR-timing-ledger
OFFICIAL_STOP_RECEIPT=receipts/REPLACE_STOP_RECEIPT.json
INPUT_RULE_MIGRATION=$D/control/$IN/rule-migration-approved.json
INPUT_TARGET_SNAPSHOT=$D/control/$IN/target-snapshot-approved.json
PROJECT_DEADLINE_UTC=REPLACE_APPROVED_DEADLINE_UTC
# R20：阶段预算按“顺利路径估算上限×1.5+30 分钟、向上取整到 15 分钟”标定，只经本参数生效（绑定项目总账后各阶段上限是到截止的总分钟数）；按本轮实测再调。
STAGE_BUDGETS="VC-0=60 VC-1=120 VC-2=210 VC-3=75 VC-4=165 VC-5=210 VC-6=165"
MIN_FREE_GIB=40
FRONTEND_DEVIATION_APPROVED_BY="REPLACE_本轮批准人日期和ARM64隔离候选适用范围"
PROFILE_ID=$TARGET_PROFILE_ID
PROFILE_DIGEST=REPLACE_APPROVED_PROFILE_SHA256
CODEX_BIN=/opt/codex-$TARGET_VERSION/bin/codex
CODEX_BIN_SHA256=REPLACE_OFFICIAL_CODEX_SHA256
OFFICIAL_ASSET_SHA256=REPLACE_OFFICIAL_PACKAGE_SHA256
MAIN_MODEL=REPLACE_MAIN_MODEL
LITE_MODEL=REPLACE_LITE_MODEL
CODEX_ACCOUNT_ID=REPLACE_CODEX_ACCOUNT_ID
API_KEY_ID=REPLACE_API_KEY_ID
POLICY_COMPAT_RECEIPT=$D/control/policy-certification/REPLACE_COMPATIBILITY.json
POLICY_ACTIVATION=$D/control/policy-certification/REPLACE_ACTIVATION.json
RELEASE_CERTIFICATION=$D/control/policy-certification/REPLACE_RELEASE.json
KILO_BIN=$D/private-tools/REPLACE_KILO/bin/kilo
KILO_VERSION=REPLACE_KILO_VERSION
KILO_SHA256=REPLACE_KILO_SHA256
COMPOSE_DIR=/root/docker/sub2apiplus/app
COMPOSE_BACKUP=/root/backups/REPLACE_COMPOSE_BACKUP.yml
PRODUCTION_IMAGE=REPLACE_VERIFIED_PRODUCTION_IMAGE
# 可选键：来源路径可覆盖默认布局；以下不可推导身份在对应入口使用前必须填好。
# stage1 必须提供官方包中 code-mode-host 的摘要与固定 digest 的采集镜像。
# TARGET_CODE_MODE_HOST_SHA256=REPLACE_CODE_MODE_HOST_SHA256
# CAPTURE_RUNTIME_IMAGE=REPLACE_PINNED_CAPTURE_IMAGE
# BASELINE_SOURCE=$D/official/codex-$BASELINE_VERSION/source-rust-v$BASELINE_VERSION/codex-rs
# TARGET_SOURCE=$D/official/codex-$TARGET_VERSION/source-rust-v$TARGET_VERSION/codex-rs
# TARGET_PACKAGE=$D/official/codex-$TARGET_VERSION/assets/codex-package-aarch64-unknown-linux-musl.tar.gz
# ACTIVE_PROFILE=$D/control/$IN/baseline-profile.json
# PREVIOUS_POLICY=$D/control/policy-certification/REPLACE_PREVIOUS_POLICY.json
# PRE_A3_CERTIFICATION=$D/control/policy-certification/REPLACE_PRE_A3.json
# 本机候选提交链要求本轮完整、已绑定 VC-3 需求的映射；canonical 要求明确退役版本。
# GATE_MAPPING_INPUT=/absolute/local/path/gate-mapping.json
# RETIRE_VERSION=8.0.0
# HISTORICAL_SOURCE_ROOT=/absolute/path/to/historical/gate/source
# JWTGEN_BIN=$D/private-tools/jwtgen
