package main

// 枚举生成：从真实画像快照导出契约所需的 typed enum。
//
// 存在的理由：第六轮我按语义**手写**枚举值，实测全错——真实值是
// `attestation_present` 不是 `attestation`、`backend_client_long_lived` 不是
// `backend_long_lived`、`h1_header_map_final_order` 不是 `h1_header_map`。
// 枚举必须从画像生成，不能靠人猜。

import (
	"encoding/json"
	"fmt"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type enumScan struct {
	Endpoints []struct {
		Compression     string `json:"Compression"`
		ClientLifecycle string `json:"ClientLifecycle"`
		HeaderOrderMode string `json:"HeaderOrderMode"`
		Query           []struct {
			Source string `json:"Source"`
		} `json:"Query"`
		Headers []struct {
			Source    string `json:"Source"`
			Condition string `json:"Condition"`
		} `json:"Headers"`
		Body struct {
			Encoding string `json:"Encoding"`
			// 真实 officialCodexBodyField 只有 Name/Required/OmitWhen/Condition。
			// 上一版这里读了一个不存在的 Source 字段——凭空信息必须从整条辅助链删净，
			// 不能因为"当前快照里它恰好为空"就留着。
			Fields []struct {
				Condition string `json:"Condition"`
				OmitWhen  string `json:"OmitWhen"`
			} `json:"Fields"`
		} `json:"Body"`
	} `json:"Endpoints"`
}

func genEnums(snapshotPath, outPath, pkgName string) error {
	if !token.IsIdentifier(pkgName) || token.Lookup(pkgName).IsKeyword() {
		return fmt.Errorf("非法 Go 包名: %q", pkgName)
	}
	snapshots, err := loadEnumSnapshots(snapshotPath)
	if err != nil {
		return err
	}
	sets := map[string]map[string]bool{
		"ConditionKind": {}, "ValueSource": {}, "OmitCondition": {},
		"CompressionKind": {}, "LifecycleKind": {}, "HeaderOrderKind": {}, "BodyEncoding": {},
	}
	add := func(k, v string) {
		sets[k][v] = true
	}
	for _, snapshot := range snapshots {
		for _, ep := range snapshot.Endpoints {
			add("CompressionKind", ep.Compression)
			add("LifecycleKind", ep.ClientLifecycle)
			add("HeaderOrderKind", ep.HeaderOrderMode)
			add("BodyEncoding", ep.Body.Encoding)
			for _, q := range ep.Query {
				add("ValueSource", q.Source)
			}
			for _, h := range ep.Headers {
				add("ValueSource", h.Source)
				add("ConditionKind", h.Condition)
			}
			for _, f := range ep.Body.Fields {
				add("ConditionKind", f.Condition)
				add("OmitCondition", f.OmitWhen)
			}
		}
	}
	prefix := map[string]string{
		"ConditionKind": "Condition", "ValueSource": "Source", "OmitCondition": "Omit",
		"CompressionKind": "Compression", "LifecycleKind": "Lifecycle",
		"HeaderOrderKind": "HeaderOrder", "BodyEncoding": "Body",
	}
	var b strings.Builder
	_, _ = b.WriteString("// Code generated by cmd/egressprofiledump -enums. DO NOT EDIT.\n")
	_, _ = b.WriteString("//\n// 枚举值取自真实画像快照，不接受手写——手写必然与画像漂移。\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	names := make([]string, 0, len(sets))
	for n := range sets {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		vals := make([]string, 0, len(sets[n]))
		for v := range sets[n] {
			vals = append(vals, v)
		}
		sort.Strings(vals)
		fmt.Fprintf(&b, "type %s string\n\nconst (\n", n)
		for _, v := range vals {
			if v == "" {
				continue
			}
			fmt.Fprintf(&b, "\t%s %s = %q\n", ident(prefix[n], v), n, v)
		}
		_, _ = b.WriteString(")\n\n")
	}
	_, _ = b.WriteString("// ObservedEnumValues 返回全部不可变快照中实际出现过的值。\n")
	_, _ = b.WriteString("func ObservedEnumValues() EnumCatalog {\n")
	_, _ = b.WriteString("\treturn mustEnumCatalog(map[EnumDomain][]string{\n")
	for _, n := range names {
		vals := make([]string, 0, len(sets[n]))
		for v := range sets[n] {
			vals = append(vals, v)
		}
		sort.Strings(vals)
		fmt.Fprintf(&b, "\t\tEnumDomain%s: {", n)
		for i, v := range vals {
			if i > 0 {
				_, _ = b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", v)
		}
		_, _ = b.WriteString("},\n")
	}
	_, _ = b.WriteString("\t})\n}\n")
	return os.WriteFile(outPath, []byte(b.String()), 0o644) //nolint:gosec // 生成命令只写入操作者指定的仓库内输出路径。
}

type enumSnapshotCatalog struct {
	Snapshots []struct {
		File string `json:"file"`
	} `json:"snapshots"`
}

// loadEnumSnapshots 同时兼容单快照和 snapshot-catalog.json。
// 目录模式会合并 active/previous 引用的全部不可变快照，旧版本独有值不会因升级被删除。
func loadEnumSnapshots(inputPath string) ([]enumScan, error) {
	raw, err := os.ReadFile(inputPath) //nolint:gosec // inputPath 来自本地维护命令显式指定的受审快照或目录。
	if err != nil {
		return nil, err
	}
	var catalog enumSnapshotCatalog
	if err := json.Unmarshal(raw, &catalog); err != nil {
		return nil, err
	}
	if len(catalog.Snapshots) == 0 {
		var snapshot enumScan
		if err := json.Unmarshal(raw, &snapshot); err != nil {
			return nil, err
		}
		return []enumScan{snapshot}, nil
	}

	baseDir := filepath.Dir(inputPath)
	out := make([]enumScan, 0, len(catalog.Snapshots))
	for _, entry := range catalog.Snapshots {
		if strings.TrimSpace(entry.File) == "" {
			return nil, fmt.Errorf("快照目录包含空文件名")
		}
		snapshotRaw, err := os.ReadFile(filepath.Join(baseDir, filepath.FromSlash(entry.File))) //nolint:gosec // entry.File 来自本地不可变快照目录，不接收网络输入。
		if err != nil {
			return nil, err
		}
		var snapshot enumScan
		if err := json.Unmarshal(snapshotRaw, &snapshot); err != nil {
			return nil, err
		}
		out = append(out, snapshot)
	}
	return out, nil
}

func ident(prefix, v string) string {
	parts := strings.Split(strings.ReplaceAll(v, ".", "_"), "_")
	var sb strings.Builder
	_, _ = sb.WriteString(prefix)
	for _, p := range parts {
		if p == "" {
			continue
		}
		_, _ = sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return sb.String()
}
