// Code generated by cmd/egressprofiledump -enums. DO NOT EDIT.
//
// 枚举值取自真实画像快照，不接受手写——手写必然与画像漂移。

package profilecontract

type BodyEncoding string

const (
	BodyFormUrlencoded               BodyEncoding = "form_urlencoded"
	BodyJson                         BodyEncoding = "json"
	BodyNone                         BodyEncoding = "none"
	BodyRawBytes                     BodyEncoding = "raw_bytes"
	BodyWebsocketDiscriminatedEvents BodyEncoding = "websocket_discriminated_events"
	BodyWebsocketJson                BodyEncoding = "websocket_json"
)

type CompressionKind string

const (
	CompressionNone                             CompressionKind = "none"
	CompressionPermessageDeflateContextTakeover CompressionKind = "permessage_deflate_context_takeover"
	CompressionZstdWhenFeatureEnabled           CompressionKind = "zstd_when_feature_enabled"
)

type ConditionKind string

const (
	ConditionAlways                    ConditionKind = "always"
	ConditionAttestationPresent        ConditionKind = "attestation_present"
	ConditionAuto                      ConditionKind = "auto"
	ConditionBetaFeaturesPresent       ConditionKind = "beta_features_present"
	ConditionCookiePresent             ConditionKind = "cookie_present"
	ConditionCreditIdPresent           ConditionKind = "credit_id_present"
	ConditionFedrampAccount            ConditionKind = "fedramp_account"
	ConditionHostedFileUpload          ConditionKind = "hosted_file_upload"
	ConditionManagedResidencyPresent   ConditionKind = "managed_residency_present"
	ConditionMemoryGeneration          ConditionKind = "memory_generation"
	ConditionParentThreadPresent       ConditionKind = "parent_thread_present"
	ConditionRemoteCompactionV2        ConditionKind = "remote_compaction_v2"
	ConditionRequestCompressionEnabled ConditionKind = "request_compression_enabled"
	ConditionResponsesLite             ConditionKind = "responses_lite"
	ConditionRuntimeMetrics            ConditionKind = "runtime_metrics"
	ConditionSessionIdPresent          ConditionKind = "session_id_present"
	ConditionSubagentPresent           ConditionKind = "subagent_present"
	ConditionTurnStatePresent          ConditionKind = "turn_state_present"
)

type HeaderOrderKind string

const (
	HeaderOrderExplicitOrder                        HeaderOrderKind = "explicit_order"
	HeaderOrderH1HeaderMapFinalOrder                HeaderOrderKind = "h1_header_map_final_order"
	HeaderOrderWsFixedPrefixThenHeaderMapSwapRemove HeaderOrderKind = "ws_fixed_prefix_then_header_map_swap_remove"
)

type LifecycleKind string

const (
	LifecycleBackendClientLongLived LifecycleKind = "backend_client_long_lived"
	LifecyclePerUpperApiCall        LifecycleKind = "per_upper_api_call"
	LifecycleReturnedUploadUrlCall  LifecycleKind = "returned_upload_url_call"
	LifecycleWebsocketConnection    LifecycleKind = "websocket_connection"
)

type OmitCondition string

const (
	OmitEmptyString            OmitCondition = "empty_string"
	OmitNone                   OmitCondition = "none"
	OmitNoneOrUnreusablePrefix OmitCondition = "none_or_unreusable_prefix"
)

type ValueSource string

const (
	SourceAccount        ValueSource = "account"
	SourceAuthentication ValueSource = "authentication"
	SourceConstant       ValueSource = "constant"
	SourceFeature        ValueSource = "feature"
	SourceGenerated      ValueSource = "generated"
	SourceManagedConfig  ValueSource = "managed_config"
	SourceModelManifest  ValueSource = "model_manifest"
	SourceProcess        ValueSource = "process"
	SourceRequestBody    ValueSource = "request_body"
	SourceServerResponse ValueSource = "server_response"
	SourceSession        ValueSource = "session"
	SourceTurn           ValueSource = "turn"
)

// ObservedEnumValues 返回全部不可变快照中实际出现过的值。
func ObservedEnumValues() EnumCatalog {
	return mustEnumCatalog(map[EnumDomain][]string{
		EnumDomainBodyEncoding:    {"form_urlencoded", "json", "none", "raw_bytes", "websocket_discriminated_events", "websocket_json"},
		EnumDomainCompressionKind: {"none", "permessage_deflate_context_takeover", "zstd_when_feature_enabled"},
		EnumDomainConditionKind:   {"", "always", "attestation_present", "auto", "beta_features_present", "cookie_present", "credit_id_present", "fedramp_account", "hosted_file_upload", "managed_residency_present", "memory_generation", "parent_thread_present", "remote_compaction_v2", "request_compression_enabled", "responses_lite", "runtime_metrics", "session_id_present", "subagent_present", "turn_state_present"},
		EnumDomainHeaderOrderKind: {"explicit_order", "h1_header_map_final_order", "ws_fixed_prefix_then_header_map_swap_remove"},
		EnumDomainLifecycleKind:   {"backend_client_long_lived", "per_upper_api_call", "returned_upload_url_call", "websocket_connection"},
		EnumDomainOmitCondition:   {"", "empty_string", "none", "none_or_unreusable_prefix"},
		EnumDomainValueSource:     {"account", "authentication", "constant", "feature", "generated", "managed_config", "model_manifest", "process", "request_body", "server_response", "session", "turn"},
	})
}
